import { jsPDF } from 'jspdf'
import { COMPANY } from '@/lib/constants'
import { formatCurrency, formatDate, generateReceiptNumber } from '@/lib/utils'

/**
 * Generate and download a payment receipt PDF
 * @param {Object} paymentData
 */
export function generateReceiptPDF(paymentData) {
    const doc = new jsPDF()
    const receiptNumber = paymentData.receiptNumber || generateReceiptNumber()

    // Colors
    const primaryColor = '#1e40af' // Blue
    const goldColor = '#eab308' // Gold

    // Header
    doc.setFillColor(30, 64, 175)
    doc.rect(0, 0, 210, 40, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text(COMPANY.name, 105, 20, { align: 'center' })

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(COMPANY.address, 105, 28, { align: 'center' })
    doc.text(`RC: ${COMPANY.rcNumber} | ${COMPANY.phone}`, 105, 34, { align: 'center' })

    // Receipt Title
    doc.setTextColor(30, 64, 175)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('PAYMENT RECEIPT', 105, 55, { align: 'center' })

    // Receipt Number
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Receipt #: ${receiptNumber}`, 20, 65)
    doc.text(`Date: ${formatDate(paymentData.date || new Date())}`, 150, 65)

    // Line
    doc.setDrawColor(200, 200, 200)
    doc.line(20, 70, 190, 70)

    // Customer Details
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Customer Details', 20, 80)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Name: ${paymentData.customerName || 'N/A'}`, 20, 88)
    doc.text(`Email: ${paymentData.customerEmail || 'N/A'}`, 20, 94)
    doc.text(`Phone: ${paymentData.customerPhone || 'N/A'}`, 20, 100)

    // Payment Details
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Payment Details', 20, 112)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')

    // Table Header
    doc.setFillColor(240, 240, 240)
    doc.rect(20, 120, 170, 8, 'F')
    doc.text('Description', 22, 126)
    doc.text('Property', 80, 126)
    doc.text('Amount', 150, 126)

    // Table Row
    doc.text(paymentData.description || 'Land Payment', 22, 136)
    doc.text(paymentData.property || 'N/A', 80, 136)
    doc.text(formatCurrency(paymentData.amount || 0), 150, 136)

    // Line
    doc.line(20, 142, 190, 142)

    // Total
    doc.setFont('helvetica', 'bold')
    doc.text('Total Paid:', 120, 150)
    doc.text(formatCurrency(paymentData.amount || 0), 150, 150)

    // Payment Method
    doc.setFont('helvetica', 'normal')
    doc.text(`Payment Method: ${paymentData.method || 'Bank Transfer'}`, 20, 162)
    doc.text(`Status: ${paymentData.status || 'Completed'}`, 20, 168)

    // Stamp Area
    doc.setDrawColor(30, 64, 175)
    doc.rect(140, 175, 50, 50)
    doc.setTextColor(30, 64, 175)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text('OFFICIAL STAMP', 165, 200, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.text(COMPANY.name, 165, 208, { align: 'center' })
    doc.text(`RC: ${COMPANY.rcNumber}`, 165, 214, { align: 'center' })
    doc.text('AUTHORIZED SIGNATURE', 165, 222, { align: 'center' })

    // Footer
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(8)
    doc.text('This is an electronically generated receipt and does not require a physical signature.', 105, 250, { align: 'center' })
    doc.text(`Generated by ${COMPANY.name} - ${COMPANY.website || 'www.happroperties.com'}`, 105, 256, { align: 'center' })

    // Save PDF
    doc.save(`Receipt_${receiptNumber}.pdf`)
}